# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine
GAMEPROJECTFILE =/home/jirka/Dokumenty/Unreal Projects/proceduralfactory/Refactory.uproject

TARGETS = \
	Refactory-Linux-DebugGame  \
	Refactory-Linux-Shipping  \
	Refactory \
	RefactoryEditor-Linux-DebugGame  \
	RefactoryEditor-Linux-Shipping  \
	RefactoryEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend RefactoryEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug RefactoryEditor-Linux-Debug


Refactory-Linux-DebugGame:
	 $(PROJECTBUILD) Refactory Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Refactory-Linux-Shipping:
	 $(PROJECTBUILD) Refactory Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Refactory:
	 $(PROJECTBUILD) Refactory Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

RefactoryEditor-Linux-DebugGame:
	 $(PROJECTBUILD) RefactoryEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

RefactoryEditor-Linux-Shipping:
	 $(PROJECTBUILD) RefactoryEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

RefactoryEditor:
	 $(PROJECTBUILD) RefactoryEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
